version: '3.4'

services:
  apigatewaymodule:
    image: apigatewaymodule
    container_name: api_gateway
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
