version: '3.4'

services:
  apicomposermodule:
    image: apicomposermodule
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8084:8084
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]
