apiVersion: v1
kind: Service
metadata:
  name: manager-mapek
  namespace: core
spec:
  selector:
    app: manager-mapek
  type: NodePort
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001