global:
  scrape_interval: 15s

# Configuration for Prometheus in local mode
# scrape_configs:
#   - job_name: 'node-exporter'
#     static_configs:
#       - targets: ['node-exporter:9100']

#   - job_name: 'docker-exporter'
#     static_configs:
#       - targets: ['docker-exporter:9417']

# Configuration for Prometheus in remote mode, monitoring exporters on specific hosts in the local network
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '192.168.1.141:9100'
          # - '192.168.1.11:9417'
          # - '192.168.1.12:9417'

  - job_name: 'docker-exporter'
    static_configs:
      - targets:
          - '192.168.1.141:9417'
