apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path