version: '3.4'

services:
  sessionmodule:
    image: sessionmodule
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8083:8083
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]
