apiVersion: v1
kind: Service
metadata:
  name: edge-service
  namespace: core
spec:
  type: NodePort
  selector:
    app: edge-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080 # Puerto externo para acceder al servicio