version: '3.4'

services:
  datarecoverymodule:
    image: datarecoverymodule
    container_name: data_recovery
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8082:8082
    volumes: 
      - .:/usr/src/app
    links: 
      - mongodb
  
  mongodb:
    image: mongo:latest
    container_name: data_recovery_db
    ports: 
      - 27012:27017
    volumes:
      - data:/data/db
  
        
volumes:
  data:
