version: '3.4'

services:
  usersmodule:
    image: usersmodule
    container_name: users
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:8081
    volumes: 
      - .:/usr/src/app
    links: 
      - mongodb
  
  mongodb:
    image: mongo:latest
    container_name: users_db
    ports: 
      - 27011:27017
    volumes:
      - data:/data/db
  
        
volumes:
  data: